branch-defaults:
  master:
    environment: poLITics-dev
    group_suffix: null
global:
  application_name: poLITics
  branch: null
  default_ec2_keyname: Heatmap Server
  default_platform: Python 2.7
  default_region: us-west-2
  profile: null
  repository: null
  sc: git
